#!/bin/bash


################## dgrid header1 ################ 
if [ x$ORIGDIR == x ]; then
export ORIGDIR=`pwd`
fi

_file0=`readlink -f $0`
cd `dirname $_file0`

. ./libdgrid.sh

################## [END] dgrid header1 ################ 

main_exit_if_not_enabled climenu

#echo 
#echo "                  << climenu CLI util   >>"
#echo 

# NOT STANDART
export MODINFO_dbg_climenu=10
climenu_run_menu $*
