#!/bin/bash

export DGRID_mode_distrubution_enable=1

################## dgrid header1 ################ 
if [ x$ORIGDIR == x ]; then
export ORIGDIR=`pwd`
fi

_file0=`readlink -f $0`
cd `dirname $_file0`

. ./libdgrid.sh

################## [END] dgrid header1 ################ 

#main_exit_if_not_enabled init

#echo 
#echo "                  << distr-dgrid >>"
#echo 
#export MODINFO_dbg_init=4
#export MODINFO_dbg_distr=10

distr_cli_main $*



