#!/bin/bash


################## dgrid header1 ################ 
if [ x$ORIGDIR == x ]; then
export ORIGDIR=`pwd`
fi

_file0=`readlink -f $0`
cd `dirname $_file0`

. ./libdgrid.sh

################## [END] dgrid header1 ################ 

main_exit_if_not_enabled init
export MODINFO_dbg_init=10

if [ -n ${MODINFO_modpath_init} ]; then
  source ${MODINFO_modpath_init}/init.bash
else
  echo "init: ERROR: MODINFO_modpath_init not set"
  exit
fi
init_cli_run init $*
