#!/bin/bash +x

################## dgrid header1 ################ 
################## [END] dgrid header1 ################ 
#echo 
#echo "                  <<  clean env >>"
#echo 
if [ "x$DGRIDBASEDIR" == x ]; then
echo "$0 : wrong env, must be called from inside dgrid processes"
exit
fi
if [ ! -d "./dgrid/" ]; then
echo pwd=`pwd`
echo "$0 : wrong env, must be called from inside dgrid processes"
echo 
exit
fi
#source ./dgrid-site/etc/dgrid.conf
#( set -o posix ; set )|grep -i ^dgrid
source ./dgrid/modules/system/generic-code.bash
source ./dgrid/modules/system/patchwork2.bash


system_f_cleanenv_do $*
