#!/bin/sh
echo ------ $0 -------

mkdir -p ${imgpack_incoming_cache}

echo imgpack_incoming_cache=$imgpack_incoming_cache
ls $imgpack_incoming_cache



# download into $imgpack_incoming_cache
imgpack_src_download 0  # $imgpack_src_file0

