#!/bin/bash

echo "================ mkdirs  ==================="

echo mkdir -p $imgpack_incoming_cache
echo mkdir -p $imgpack_cache_result
echo mkdir -p $imgpack_unpack_workdir

imgpack_ask


imgpack_util_mkdir_p $imgpack_incoming_cache
imgpack_util_mkdir_p $imgpack_unpack_workdir
imgpack_util_mkdir_p $imgpack_cache_result
