#!/bin/bash
echo "--------- SET VARS ------------"

export imgpack_incoming_cache="$HOME/.cache/dgrid/imgpack/${imgpack_id_name}"
export imgpack_cache_result="$HOME/.cache/dgrid/imgpack/${imgpack_id_name}--result"
export imgpack_unpack_workdir="$HOME/tmp/dgrid/imgpack/${imgpack_id_name}"

