#!/bin/bash


################## dgrid header1 ################ 
if [ x$ORIGDIR == x ]; then
export ORIGDIR=`pwd`
fi

_file0=`readlink -f $0`
cd `dirname $_file0`

. ./libdgrid.sh

################## [END] dgrid header1 ################ 

main_exit_if_not_enabled run

#export MODINFO_dbg_run=15
#export MODINFO_dbg_nodecfg=15
#export MODINFO_dbg_cfgstack=15
#export CONNECT_type_override="local"
#export CONNECT_type_override="ssh"
#export RUN_DRY_RUN=Y

run_nodecmd $*

